### ISSUE TITLE
nightly fails due to inavaiability of dependencies for py 3.7-dev

### ISSUE THREAD

**Issue by AmitAronovitch** [satellogic/quaternions#21]
This time PyYAML fails to compile from source
blocks #20 
I suggest we allow failures in nightly...
```
matrix:
  allow_failures:
    - python: "nightly"
```

**Comment by Juanlu001** [comment]
The failure was already reported upstream:

https://github.com/yaml/pyyaml/issues/152

I agree it would be more sensible to allow nightly failures.
